# This is used to figure out how the system should optimize itself.
# memory: This mode is only advisable if your system is VERY short on memory.
#     Almost every other use case this is not the preferable approach.
# process: This is the default mode. The system will try to reduce the processing
#    rather than reduce memory usage wherever possible.
optimization: process

# The maximum number of factions allowed on the server.
# Set this to -1 to disable the feature entirely.
max-factions: -1

# All the options related to the factions themselves
factions:
  # The defaults for the factions.
  defaults:
    # The default default-role that factions have when they are created.
    default-role:
      # Options: trial, member, moderator, admin
      role: member
      # Whether or not factions are allowed to change the default-role
      changeable: true
  names:
    warzone: Warzone
    safezone: Safezone
    wilderness: Wilderness
    normal: Faction

# Configuration for how the system stores the Faction data.
storage:
  # The type of storage to use. The options available are:
  # mongodb, json, mysql
  # If you choose to use a database, remember it is only faster and more efficient if your database
  #    are both hosted on the same server box.
  type: mongodb
  # Database options. Only relevant if you choose to use mongodb or mysql.
  database:
    hostname: localhost
    port: 27017
    username: root
    password: password
    database: factions 
    timeout: 100
    description: 'Factions Connection'

# All configuration related to creating a new Faction
create:
  # The economy cost of creating a Faction
  cost: 0
  # If the creation of the faction should be broadcast.
  broadcast: true
  # If the command to run a command can be cancelled by another plugin.
  cancellable:
    enabled: true
    silent: false